name: Test

on: [push]

jobs:

  test:
    name: Unit test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Update pip
      run: |
        python -m pip install --upgrade pip
    - name: Install project dependencies
      run: |
        pip install boto3
        pip install moto[s3]
        pip install pytest
    - name: Test
      run: |
        pytest -sv test
